language: python
python: 2.7
env:
    - TOX_ENV=py34
    - TOX_ENV=pep8
install: "pip install tox"
script:
    - cp WhatManager3/settings.example.dev.py WhatManager3/settings.py
    - tox -e $TOX_ENV
